namespace :bool_nanny do 
  desc 'rake tasks generated by the bool_nanny gem'
  task :nil_to_false do 
    desc '
      takes all existing booleans that allow nil and disallows nil.
      If no default is set, the default is set to false.
      In the DB, all values the default value.
      '
    load File.expand_path(__FILE__+'/../../generators/change_null_bool_defaults_to_false.rb')
  end
end